packages:
  - apps/*
  - packages/*

autoInstallPeers: false

allowBuilds:
  '@parcel/watcher': true
  '@prisma/engines': true
  '@swc/core': true
  '@tarojs/binding': true
  '@tarojs/cli': true
  core-js: false
  core-js-pure: false
  esbuild: true
  prisma: true

catalogMode: strict

linkWorkspacePackages: true

minimumReleaseAgeExclude:
  - '@typescript-eslint/eslint-plugin@8.65.0'
  - '@typescript-eslint/parser@8.65.0'
  - '@typescript-eslint/project-service@8.65.0'
  - '@typescript-eslint/scope-manager@8.65.0'
  - '@typescript-eslint/tsconfig-utils@8.65.0'
  - '@typescript-eslint/type-utils@8.65.0'
  - '@typescript-eslint/types@8.65.0'
  - '@typescript-eslint/typescript-estree@8.65.0'
  - '@typescript-eslint/utils@8.65.0'
  - '@typescript-eslint/visitor-keys@8.65.0'
  - prettier@3.9.6
  - typescript-eslint@8.65.0

preferWorkspacePackages: true

saveExact: true

strictPeerDependencies: true

catalog:
  dotenv: 17.4.2
  prisma: 7.9.0
