packages:
  - apps/*
  - packages/*

autoInstallPeers: false

allowBuilds:
  '@parcel/watcher': true
  '@prisma/engines': true
  '@scarf/scarf': false
  core-js: false
  core-js-pure: false
  esbuild: true
  prisma: true

catalogMode: strict

linkWorkspacePackages: true

minimumReleaseAgeExclude:
  - '@prisma/config@7.9.0'
  - '@prisma/debug@7.9.0'
  - '@prisma/engines@7.9.0'
  - '@prisma/fetch-engine@7.9.0'
  - '@prisma/get-platform@7.9.0'
  - '@typescript-eslint/eslint-plugin@8.65.0'
  - '@typescript-eslint/parser@8.65.0'
  - '@typescript-eslint/project-service@8.65.0'
  - '@typescript-eslint/scope-manager@8.65.0'
  - '@typescript-eslint/tsconfig-utils@8.65.0'
  - '@typescript-eslint/type-utils@8.65.0'
  - '@typescript-eslint/types@8.65.0'
  - '@typescript-eslint/typescript-estree@8.65.0'
  - '@typescript-eslint/utils@8.65.0'
  - '@typescript-eslint/visitor-keys@8.65.0'
  - prettier@3.9.6
  - prisma@7.9.0
  - typescript-eslint@8.65.0
  - '@prisma/adapter-pg@7.9.0'
  - '@prisma/client-runtime-utils@7.9.0'
  - '@prisma/client@7.9.0'
  - '@prisma/driver-adapter-utils@7.9.0'
  - brace-expansion@5.0.8

overrides:
  adm-zip@<0.6.0: 0.6.0
  brace-expansion@<=5.0.7: 5.0.8
  find-my-way: 9.7.0
  glob: 10.5.0
  http-cache-semantics@<4.1.1: 4.1.1
  jpeg-js@<0.4.4: 0.4.4
  minimist@<0.2.4: 0.2.4
  postcss@<8.5.18: 8.5.20
  serialize-javascript@<=7.0.2: 7.0.3
  swiper: 'catalog:'

preferWorkspacePackages: true

saveExact: true

strictPeerDependencies: true

catalog:
  '@nestjs/swagger': 11.4.5
  '@node-rs/argon2': 2.0.2
  '@playwright/test': 1.61.1
  '@prisma/adapter-pg': 7.9.0
  '@prisma/client': 7.9.0
  class-transformer: 0.5.1
  class-validator: 0.15.1
  dotenv: 17.4.2
  exceljs: 4.4.0
  husky: 9.1.7
  jose: 5.10.0
  lint-staged: 17.1.0
  pg: 8.22.0
  prisma: 7.9.0
  redis: 6.1.0
  swiper: 12.1.2
